server:
  port: 8080
  servlet:
    context-path: /music

spring:
  application:
    name: music crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/music?allowPublicKeyRetrieval=true&sslMode=DISABLED&userSLL=false&serverTimezone=UTC
    username: docker
    password: docker
